[package]
name = "shunyadb"
version = "0.1.0"
edition = "2024"

[dependencies]
lru = "0.12"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
clap = { version = "4", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
